module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EOA9RbQ8MTx0pDc2dgYJ6A               ', 
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://ibb.co/0jwyWY6Q.  ',
    NEWSLETTER_JID: '120363420907749813@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ʜ ᴀ ꜱ ɪ ᴛ ʜ ᴀ ᴍɪɴɪ ʙᴏᴛ ᴠ1',
    OWNER_NAME: 'HASITHA YOVI',
    OWNER_NUMBER: '94705846788',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʟ ᴏ ᴋ ᴜ  ʜ ᴀ ꜱ ɪ ᴛ ʜ ᴀ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb78JuB4NVimBRUhJ43o,
};
